// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChangeFileName: typeof import('./src/components/ChangeFileName/index.vue')['default']
    copy: typeof import('./src/components/DelFile copy/index.vue')['default']
    Create: typeof import('./src/components/Create/index.vue')['default']
    Delfile: typeof import('./src/components/Delfile/index.vue')['default']
    DelFile: typeof import('./src/components/DelFile/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ExitLogin: typeof import('./src/components/ExitLogin/index.vue')['default']
    FileList: typeof import('./src/components/FileList/index.vue')['default']
    HightLine: typeof import('./src/components/HightLine/index.vue')['default']
    IconList: typeof import('./src/components/IconList/index.vue')['default']
    Idnex: typeof import('./src/components/HightLine/idnex.vue')['default']
    LightParsing: typeof import('./src/components/LightParsing/index.vue')['default']
    Login: typeof import('./src/components/Login/index.vue')['default']
    MDEdit: typeof import('./src/components/MDEdit/index.vue')['default']
    MiniList: typeof import('./src/components/MiniList/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SA: typeof import('./src/components/SA/index.vue')['default']
    Search: typeof import('./src/components/Search/index.vue')['default']
    Setting: typeof import('./src/components/Setting/index.vue')['default']
    SettingConfig: typeof import('./src/components/SettingConfig/index.vue')['default']
    SettingMD: typeof import('./src/components/SettingMD/index.vue')['default']
    SettingMenu: typeof import('./src/components/SettingMenu/index.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar/index.vue')['default']
    Upload: typeof import('./src/components/Upload/index.vue')['default']
    UserInit: typeof import('./src/components/UserInit/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
